image:
        #centos/python-36-centos7:latest
        #yumoshangguan/csvkit-python-36-centos7
        #yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.3
        #yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.4
        #yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.5-install_tool_called_file
        yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.6-setDufaultEncoding_utf8_for_python3.6

stages:
        - test_environment

test_project:
        stage: test_environment
        tags:
                - G1-C
        script:
                - pwd
                #- chmod +x ./scriptsForDataPreprocess/dataItemSelect.sh
                - ./scriptsForDataPreprocess/dataItemSelect.sh
