image:
        #centos/python-36-centos7:latest
        #yumoshangguan/csvkit-python-36-centos7
        #yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.3
        #yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.4
        yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.5-install_tool_called_file

stages:
        - processing_dataset

##2019-11-29-01
#processing_dataset_2017:
#        stage: processing_dataset
#        tags:
#                - S4-C
#                #- S4-B
#        script:
#                - chmod 777 -R /mnt/shared/Datasets/bobowang/For_this_Experimen/trace_201708
#                #- pwd
#                #- chmod +x ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017.sh
#                #- ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017.sh
#                - gcc -std=c99 -g -w -o ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017 ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017.c -lpthread -lm
#                - ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017 2 > /mnt/shared/Datasets/bobowang/For_this_Experiment/trace_201708/processing_dataset_2017-log.log

#                #- chmod +x ./scriptsForDataPreprocess/dataItemSelect_2017.sh
#                #- ./scriptsForDataPreprocess/dataItemSelect_2017.sh

processing_dataset_2018:
        stage: processing_dataset
        tags:
                - G1-C
        script:
                - chmod 777 -R /mnt/shared/Datasets/bobowang/For_this_Experimen/alibaba_clusterdata_v2018
                #- pwd
                #- chmod +x ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2018.sh
                #- ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2018.sh
                - gcc -std=c99 -g -w -o ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2018 ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2018.c -lpthread -lm
                - ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2018 1 2 3 > /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/processing_dataset_2018-log.log
                #- chmod +x ./scriptsForDataPreprocess/dataItemSelect_2018.sh
                #- ./scriptsForDataPreprocess/dataItemSelect_2018.sh


##2019-12-05-01
#select_dataset_2017:
#        stage: processing_dataset
#        tags:
#                #- S4-C
#                - S4-B
#                #- G1-C
#        script:
#                - chmod 777 -R /mnt/shared/Datasets/bobowang/For_this_Experimen/trace_201708
#                - pwd
#                - ls -alh
#                - chmod +x ./dataItemSelect_2017.sh
#                - ./dataItemSelect_2017.sh
#
#select_dataset_2018:
#        stage: processing_dataset
#        tags:
#                #- S4-C
#                #- S4-B
#                - G1-C
#        script:
#                - chmod 777 -R /mnt/shared/Datasets/bobowang/For_this_Experimen/alibaba_clusterdata_v2018
#                - pwd
#                - ls -alh
#                - chmod +x ./dataItemSelect_2018.sh
#                - ./dataItemSelect_2018.sh

##2019-12-08-001
#look_for_dataset_2018:
#        stage: processing_dataset
#        tags:
#                - G1-C
#        script:
#                - chmod 777 -R /mnt/shared/Datasets/bobowang/For_this_Experimen/alibaba_clusterdata_v2018
#                - mkdir -p /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/look
#                - head -3000 /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/batch_instance-effective.csv > /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/look/batch_instance-effective.csv
#                - head -3000 /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/batch_instance-usable.csv > /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/look/batch_instance-usable.csv
#                - head -3000 /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/batch_instance.csv > /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/look/batch_instance.csv
#                - head -3000 /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/midstFile/clustered_column_1_based-batch_instance-effective.csv.backup > /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/look/clustered_column_1_based-batch_instance-effective.csv.backup
#                - head -3000 /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/midstFile/clustered_column_3_based-batch_instance-effective.csv.backup > /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/look/clustered_column_3_based-batch_instance-effective.csv.backup
#                - head -3000 /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/midstFile/clustered_column_5_based-batch_instance-effective.csv.backup > /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/look/clustered_column_5_based-batch_instance-effective.csv.backup
#                - head -3000 /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/midstFile/clustered_column_7_based-batch_instance-effective.csv.backup > /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/look/clustered_column_7_based-batch_instance-effective.csv.backup
#                - head -3000 /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/midstFile/clustered_column_9_based-batch_instance-effective.csv.backup > /mnt/shared/Datasets/bobowang/For_this_Experiment/alibaba_clusterdata_v2018/look/clustered_column_9_based-batch_instance-effective.csv.backup
