image:
        #centos/python-36-centos7:latest
        #yumoshangguan/csvkit-python-36-centos7
        #yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.3
        #yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.4
        yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.5-install_tool_called_file

stages:
        - processing_dataset

#2019-11-29-01
#processing_dataset_2017:
#        stage: processing_dataset
#        tags:
#                #- S4-C
#                - S4-B
#        script:
#                #- pwd
#                #- chmod +x ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017.sh
#                #- ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017.sh
#                #- rm -f ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017
#                - gcc -std=c99 -g -w -o ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017 ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017.c -lpthread -lm
#                - ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017
#                #- chmod +x ./scriptsForDataPreprocess/dataItemSelect_2017.sh
#                #- ./scriptsForDataPreprocess/dataItemSelect_2017.sh

processing_dataset_2018:
        stage: processing_dataset
        tags:
                - G1-C
        script:
                #- pwd
                #- chmod +x ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2018.sh
                #- ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2018.sh
                #- rm -f ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2018
                - gcc -std=c99 -g -w -o ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2018 ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2018.c -lpthread -lm
                - ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2018 2
                #- chmod +x ./scriptsForDataPreprocess/dataItemSelect_2018.sh
                #- ./scriptsForDataPreprocess/dataItemSelect_2018.sh


##2019-12-05-01
#select_dataset_2017:
#        stage: processing_dataset
#        tags:
#                #- S4-C
#                - S4-B
#                #- G1-C
#        script:
#                - pwd
#                - ls -alh
#                - chmod +x ./dataItemSelect_2017.sh
#                - ./dataItemSelect_2017.sh
#
#select_dataset_2018:
#        stage: processing_dataset
#        tags:
#                #- S4-C
#                #- S4-B
#                - G1-C
#        script:
#                - pwd
#                - ls -alh
#                - chmod +x ./dataItemSelect_2018.sh
#                - ./dataItemSelect_2018.sh

