image:
        #centos/python-36-centos7:latest
        #yumoshangguan/csvkit-python-36-centos7
        yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.3

stages:
        - test_environment

test_project:
        stage: test_environment
        tags:
                - G1-C
        script:
                - pwd
                - echo "这是测试！"
                - python --version
                - python3 --version
                - gcc --version
                #- ls -alh
                - ls -alh ./scriptsForDataPreprocess/dataItemSelect.sh
                #- chmod +x ./scriptsForDataPreprocess/dataItemSelect.sh
                - ./scriptsForDataPreprocess/dataItemSelect.sh
