image:
        #centos/python-36-centos7:latest
        #yumoshangguan/csvkit-python-36-centos7
        #yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.3
        #yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.4
        yumoshangguan/centos7.7.1908-gcc8.3.0-python3.6:v0.0.5-install_tool_called_file

stages:
        - processing_dataset

processing_dataset_2017:
        stage: processing_dataset
        tags:
                - S4-C
        script:
                #- pwd
                - chmod +x ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017.sh
                - ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017.sh
                - chmod +x ./scriptsForDataPreprocess/dataItemSelect_2017.sh
                #- ./scriptsForDataPreprocess/dataItemSelect_2017.sh

processing_dataset_2018:
        stage: processing_dataset
        tags:
                - G1-C
        script:
                #- pwd
                - chmod +x ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2017.sh
                - ./scriptsForDataPreprocess/generateNumToSelectDatasetRandomly_2018.sh
                - chmod +x ./scriptsForDataPreprocess/dataItemSelect_2018.sh
                #- ./scriptsForDataPreprocess/dataItemSelect_2018.sh
